[package]
name = "portal-router"
version = "0.0.0"
authors = []
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3"
log = "0.4"
fern = "0.6"
screeps-game-api = "0.15"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
web-sys = { version = "0.3", features = ["console"] }
base64 = "0.21.2"

[profile.release]
panic = "abort"
opt-level = 3
lto = true

[package.metadata.wasm-pack.profile.release]
strip = true
#wasm-opt = ["-O4", "--disable-sign-ext"]
wasm-opt = false

[features]
default = []
